# Enable Colours
set -g default-terminal "xterm-256color"
set -as terminal-features ",xterm-256color:RGB"

# Map Default Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Split Windows
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Pane Navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Reload Config
unbind r
bind r source-file ~/.tmux.conf

# Resize Panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Enable Mouse
set -g mouse on

# Terminal Scrollback
set -g history-limit 50000

# Enable vim motions
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Enable Mouse Dragging
unbind -T copy-mode-vi MouseDragEnd1Pane


# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'off'
set -g @continuum-restore 'off'

# Theme
set -g @themepack 'powerline/double/orange'


run '~/.tmux/plugins/tpm/tpm'



